#!/bin/bash
# 关于 texlive/xelatex 的中文输入
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#%只要有相应的字体文档，不需要使用CJKutf8，直接由 xelatex 产生pdf文档	%
#%检索安装字体用命令 fc-list | grep'字体名' 即可知道可用字体		%
#%									%
#\usepackage{fontspec}							%
#\setmainfont[Mapping=tex-text]{LiSu}					%
#%\setmainfont[Mapping=tex-text]{Adobe 宋体 Std}	%article用字体	%
#%\setsansfont[Mapping=tex-text]{Adobe 黑体 Std}	 %Beamer用字体	%
#%									%
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

touch 01_Latex_Template/.tmp 
test -s 01_Latex_Template/Content-2-Main.tex && sed 's/^\\input/%\\input/g' 01_Latex_Template/Content-2-Main.tex  > 01_Latex_Template/.tmp || echo "%Main_File"  > 01_Latex_Template/.tmp
test -e 01_Latex_Template/Content-2-Main.tex && echo "%Main_File"  > 01_Latex_Template/.tmp
sed '$a%%%%%%%%%%  '"$1"'   %%%%%%%%%%  \n\\\input{'"$1"'}' 01_Latex_Template/.tmp  > 01_Latex_Template/Content-2-Main.tex 
rm 01_Latex_Template/.tmp 

xelatex Latex_2020-Template
bibtex Latex_2020-Template
xelatex Latex_2020-Template
xelatex Latex_2020-Template
rm -rf *.bak *.log  *.dvi *.out *.nav *.thm *.snm *.toc *.xml *.*~ *~ .Latex_2020-Template.*.swp *.aux *.bbl *.blg
mv Latex_2020-Template.pdf $1.pdf
evince $1.pdf
